# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: MaskAI CI/CD Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Code standard analysing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with pylint
      run: |
        PYTHONIOENCODING=utf-8 pylint app/ src/ tests/ --fail-under=8 --output-format=colorized

    - name: Test with pytest
      run: |
        pytest